---

- hosts: all
  tasks:

  - name: "Setup the required folders."
    script: "../scripts/conf_repos.sh setup_folders"
    args:
      executable: "/bin/bash"

  - name: "Cloning repositories"
    git:
      repo: "git@github.com:juselara1/{{ item }}"
      dest: "~/.config/{{ item }}"
      force: yes
    loop: [
      "zathura", "kitty", "nvim", "shell_scripts", "qtile",
      "starship", "ipython", "rofi", "qutebrowser"
      ]

  - name: "Copying config files"
    copy:
      src: "../confs/{{ item }}"
      dest: "~/.{{ item }}"
    loop: ["bashrc", "tmux.conf", "inputrc", "xinitrc"]
