---

- hosts: arch
  become: true
  tasks:

  - name: "Update and upgrade kernel."
    pacman:
      update_cache: yes
      upgrade: yes

  - name: "Installing general-purpose programs."
    pacman:
      name: [
        "zathura", "zathura-pdf-mupdf", "zathura-djvu",
        "zathura-ps", "rofi", "flameshot", "qutebrowser",
        "sxiv", "inkscape", "alsa-utils"
      ]
      state: latest

- hosts: debian
  become: true
  tasks:

  - name: "Update and upgrade kernel."
    apt:
      update_cache: yes
      upgrade: yes

  - name: "Installing general-purpose programs."
    apt:
      name: [
        "zathura", "zathura-djvu", "zathura-ps",
        "rofi", "flameshot", "qutebrowser", "sxiv", "inkscape",
        "alsa-utils"
      ]
      state: latest

- hosts: all
  become: true
  tasks:

  - name: "Installing starship"
    script: "../scripts/installation.sh install_starship"
    args:
      executable: "/bin/bash"

  - name: "Downloading just terminal"
    git:
      repo: "https://github.com/juselara1/just.git"
      version: "main"
      dest: "/tmp/just"
      force: yes

  - name: "Install just"
    script: "../scripts/installation.sh install_just"
    args:
      executable: "/bin/bash"
