---

- hosts: arch
  become: true
  tasks:

  - name: "Update and upgrade kernel."
    pacman:
      update_cache: yes
      upgrade: yes

  - name: "Installing general-purpose programs."
    pacman:
      name: [
        "zathura", "zathura-pdf-mupdf", "zathura-djvu",
        "zathura-ps", "rofi", "flameshot", "qutebrowser",
        "sxiv", "inkscape", "alsa-utils"
      ]
      state: latest

  - name: "Installing alacritty dependences"
    pacman:
      name: [
        "cmake", "freetype2", "fontconfig", "pkg-config", "make", "libxcb", "libxkbcommon" 
    ]

- hosts: debian
  become: true
  tasks:

  - name: "Update and upgrade kernel."
    apt:
      update_cache: yes
      upgrade: yes

  - name: "Installing general-purpose programs."
    apt:
      name: [
        "zathura", "zathura-djvu", "zathura-ps",
        "rofi", "flameshot", "qutebrowser", "sxiv", "inkscape",
        "alsa-utils"
      ]
      state: latest

  - name: "Installing alacritty dependences"
    apt:
      name: [
        "cmake", "pkg-config", "libfreetype6-dev", "libfontconfig1-dev",
        "libxcb-xfixes0-dev", "libxkbcommon-dev"
    ]

- hosts: all
  become: true
  tasks:

  - name: "Installing starship"
    script: "../scripts/installation.sh install_starship"
    args:
      executable: "/bin/bash"

  - name: "Downloading alacritty terminal"
    git:
      repo: "https://github.com/alacritty/alacritty"
      version: "master"
      dest: "/tmp/alacritty"
      force: yes

  - name: "Installing rustup"
    script: "../scripts/installation.sh install_rustup"
    args:
      executable: "/bin/bash"

  - name: "Install alacritty"
    script: "../scripts/installation.sh install_alacritty"
    args:
      executable: "/bin/bash"
