---

- hosts: "arch"
  become: true
  tasks:
  - name: "Setting up pyenv"
    pacman:
      name: ["pyenv"]

- hosts: "debian"
  become: true
  tasks:

  - name: "Setting up pyenv dependences"
    apt:
      name: [
        "zlib1g-dev", "libffi-dev", "libssl-dev",
        "libbz2-dev", "libreadline-dev", "libsqlite3-dev",
        "liblzma-dev", "python3-venv"
      ]
      state: "latest"
