---

- hosts: all
  tasks:

  - name: "Setup the required folders."
    script: "../scripts/ssh_utils.sh setup_folders"
    args:
      executable: "/bin/bash"

  - name: "Copy ssh config"
    copy:
      src: "../confs/ssh_config"
      dest: "~/.ssh/config"
      remote_src: no

  - name: "Generate ssh keys"
    script: "../scripts/ssh_utils.sh generate_keys {{ email }} {{ file_name }}"
    args:
      executable: "/bin/bash"
    register: out
    vars:
      email: "julara@unal.edu.co"
      file_name: "id_rsa"
  - debug: msg="{{ out }}"
